apps/gradehoraria/urls.py
from django.urls import path

from . import views

app_name = 'gradehoraria'

urlpatterns = [
    path('professores', views.listar_professores, name='listar_professores'),
    path('professores/adicionar/', views.adicionar_professor, name='adicionar_professor'),
    path('professores/editar/<int:id_professor>/', views.editar_professor, name='editar_professor'),
    path('professores/excluir/<int:id_professor>/', views.deleta_professor, name='deleta_professor'),

    path('cursos', views.listar_cursos, name='listar_cursos'),
    path('curso/adicionar/', views.adicionar_curso, name='adicionar_curso'),
    path('curso/editar/<int:id_curso>/', views.editar_curso, name='editar_curso'),
    path('curso/excluir/<int:id_curso>/', views.deleta_curso, name='deleta_curso'),

    path('disciplinas', views.listar_disciplinas, name='listar_disciplinas'),
    path('disciplina/adicionar/', views.adicionar_disciplina, name='adicionar_disciplina'),
    path('disciplina/editar/<int:id_disciplina>/', views.editar_disciplina, name='editar_disciplina'),
    path('disciplina/excluir/<int:id_disciplina>/', views.deleta_disciplina, name='deleta_disciplina'),

    path('turmas', views.listar_turmas, name='listar_turmas'),
    path('turma/adicionar/', views.adicionar_turma, name='adicionar_turma'),
    path('turma/editar/<int:id_turma>/', views.editar_turma, name='editar_turma'),
    path('turma/excluir/<int:id_turma>/', views.deleta_turma, name='deleta_turma'),  path('turmas', views.listar_turmas, name='listar_turmas'),

    path('salas', views.listar_salas, name='listar_salas'),
    path('sala/adicionar/', views.adicionar_sala, name='adicionar_sala'),
    path('sala/editar/<int:id_sala>/', views.editar_sala, name='editar_sala'),
    path('sala/excluir/<int:id_sala>/', views.deleta_sala, name='deleta_sala'),

    path('oferta/adicionar/', views.adicionar_oferta, name='adicionar_oferta'),
    path('oferta/listar/', views.listar_ofertas, name='listar_ofertas'),
    path('oferta/listar/<int:turma>/', views.listar_ofertas, name='listar_ofertas'),
    path('oferta/editar/<int:id_oferta>/', views.editar_oferta, name='editar_oferta'),
    path('oferta/excluir/<int:id_oferta>/', views.deleta_oferta, name='deleta_oferta'),

    path('parametros/adicionar/', views.adicionar_parametros, name='adicionar_parametros'),
    path('parametros/listar/', views.listar_parametros, name='listar_parametros'),
    path('parametros/editar/<int:id_parametro>/', views.editar_parametros, name='editar_parametros'),

    path('grade/gerar_grade/', views.gerarGradeHoraria, name='gerarGradeHoraria'),
    path('grade/listar_grades/', views.listar_grades, name='listar_grades'),
    path('grade/editar/<int:id_turma>/', views.editar_grade, name='editar_grade'),
    path('grade/mostrar/<int:id_turma>/', views.mostrar_grade, name='mostrar_grade'),
    path('grade/excluir/<int:paramTurma_id>/', views.deleta_grade, name='deleta_grade'),
    # path('grade/salvarGrade/<List:resultado>/', views.salvarGradeHoraria, name='salvarGradeHoraria'),

    #path('', views.gradeHoraria, name='hello_world'),
    #path('', views.index, name='index'),
]

gradehorariaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gradehoraria/', include('gradehoraria.urls', namespace='gradehoraria')),
    path('contas/', include('contas.urls', namespace='contas')),
    path('', include('core.urls', namespace='core')),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name='contas/password_reset.html'),
         name='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='contas/password_reset_sent.html'),
         name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='contas/password_reset_form.html'),
         name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='contas/password_reset_done.html'),
         name='password_reset_complete'),

    #path('grade/', TemplateView.as_view(template_name='grade.html')),
    #path('cadastrarProfessor', TemplateView.as_view(template_name='professor.html')),
    #path('', TemplateView.as_view(template_name='home.html')),
]

apps/gradehoraria/forms.py
from django import forms

from .models import Professor, Horario, Sala, Curso, Turma, Disciplina, Oferta, Grade, ParametrosGrade, Gene


class ProfessorForm(forms.ModelForm):
    # turno = forms.CharField(label="Turno", required=True)
    # disponibilidade = forms.CharField(label="disponibilidade", required=False)

    # def listar_disciplinas(self, obj):
    #     return ", ".join(c.sigla_disciplina for c in obj.disciplinas.all())
    #
    # listar_disciplinas.short_description = "Disciplinas"

    class Meta:
        model = Professor
        fields = ('nm_professor', 'matricula', 'disciplinas')
        #fields = '__all__'


class HorarioForm(forms.ModelForm):
    class Meta:
        model = Horario
        fields = '__all__'


class SalaForm(forms.ModelForm):
    class Meta:
        model = Sala
        fields = '__all__'


class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = '__all__'


class TurmaForm(forms.ModelForm):
    class Meta:
        model = Turma
        fields = '__all__'
        #exclude = ['professor_id', 'disciplina_id']


class DisciplinaForm(forms.ModelForm):
    class Meta:
        model = Disciplina
        fields = '__all__'


class OfertaForm(forms.ModelForm):
    class Meta:
        model = Oferta
        fields = '__all__'


class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = '__all__'


class ParametrosGradeForm(forms.ModelForm):
    class Meta:
        model = ParametrosGrade
        exclude = ('taxaMutacao',)


class GeneForm(forms.ModelForm):
    class Meta:
        model = Gene
        fields = '__all__'

apps/gradehoraria/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.db import transaction
from more_itertools import unique_everseen
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.db import connection

from .forms import ProfessorForm, DisciplinaForm, CursoForm, TurmaForm, HorarioForm, SalaForm, OfertaForm, ParametrosGradeForm, GeneForm
from .models import Disciplina, Curso, Professor, Turma, Horario, Sala, Oferta, ParametrosGrade, Gene, Grade

import random
import itertools


@staff_member_required(login_url='/')
@login_required(login_url='/contas/login')
def adicionar_professor(request):
    template_name = 'professor/adicionar_professor.html'
    if request.method == 'POST':
        form = ProfessorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Professor cadastrado com sucesso!')
            return redirect('gradehoraria:listar_professores')
        else:
            messages.warning(request, 'Erro ao cadastrar novo professor!')
    else:
        form = ProfessorForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)


@login_required(login_url='/contas/login')
def listar_professores(request):
    templane_name = 'professor/listar_professores.html'
    professores = Professor.objects.prefetch_related('disciplinas')

    for p in professores    :
        print(p)
    context = {
        'professores': professores
    }
    return render(request, templane_name, context)


@login_required(login_url='/contas/login')
def editar_professor(request, id_professor):
    template_name = 'professor/adicionar_professor.html'
    context = {}
    editar_professor = get_object_or_404(Professor, id_professor=id_professor)
    if request.method == 'POST':
        form = ProfessorForm(request.POST, instance=editar_professor)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados do professor alterados com sucesso!')
            return redirect('gradehoraria:listar_professores')
        else:
            messages.error(request, 'Erro ao alterar dados do professor')
    else:
        form = ProfessorForm(instance=editar_professor)
        context['form'] = form
        return render(request, template_name, context)


# FIXME: Criar confirmação de exclusão antes de persistir no banco - OK
@login_required(login_url='/contas/login')
def deleta_professor(request, id_professor):
    deleteProfessor = Professor.objects.get(id_professor=id_professor)
    deleteProfessor.delete()
    messages.warning(request, 'Professor excluído com sucesso!')
    return redirect('gradehoraria:listar_professores')


@login_required(login_url='/contas/login')
def adicionar_disciplina(request):
    if request.method == 'POST':
        form = DisciplinaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Disciplina cadastrada com sucesso!')
            return redirect('gradehoraria:listar_disciplinas')
        else:
            messages.error(request, 'Erro ao cadastrar disciplina!')
    else:
        if request.user.is_staff:
            form = DisciplinaForm()
            return render(request, 'disciplina/adicionar_disciplina.html', {'form': form})
        else:
            messages.error(request, 'Usuário sem permissão para cadastrar disciplinas!')
            return redirect('gradehoraria:listar_disciplinas')


@login_required(login_url='/contas/login')
def listar_disciplinas(request):
    disciplinas = Disciplina.objects.all()
    return render(request, 'disciplina/listar_disciplinas.html', {'disciplinas': disciplinas})


# FIXME: Criar confirmação de exclusão antes de persistir no banco - OK
@login_required(login_url='/contas/login')
def deleta_disciplina(request, id_disciplina):
    if request.user.is_staff:
        deleteDisciplina = Disciplina.objects.get(id_disciplina=id_disciplina).delete()
        messages.warning(request, 'Disciplina excluída com sucesso!')
    else:
        messages.error(request, 'Você não pode excluir disciplinas.')
        return render(request, 'base.html')
    return redirect('gradehoraria:listar_disciplinas')


@login_required(login_url='/contas/login')
def editar_disciplina(request, id_disciplina):
    editar_disciplina = get_object_or_404(Disciplina, id_disciplina=id_disciplina)
    if request.method == 'POST':
        form = DisciplinaForm(request.POST, instance=editar_disciplina)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados da disciplina alterados com sucesso!')
            return redirect('gradehoraria:listar_disciplinas')
        else:
            messages.error(request, 'Erro ao alterar dados da disciplina')
    else:
        form = DisciplinaForm(instance=editar_disciplina)
        return render(request, 'disciplina/adicionar_disciplina.html', {'form': form})


@login_required(login_url='/contas/login')
def adicionar_curso(request):
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Curso cadastrado com sucesso!')
            return redirect('gradehoraria:listar_cursos')
        else:
            messages.error(request, 'Erro ao cadastrar o curso!')
    else:
        form = CursoForm()
    return render(request, 'curso/adicionar_curso.html', {'form': form})


@login_required(login_url='/contas/login')
def listar_cursos(request):
    cursos = Curso.objects.all()
    return render(request, 'curso/listar_cursos.html', {'cursos': cursos})


# FIXME: Criar confirmção de exclusão antes de persistir no banco
@login_required(login_url='/contas/login')
def deleta_curso(request, id_curso):
    deleteCurso = Curso.objects.get(id_curso=id_curso)
    deleteCurso.delete()
    messages.warning(request, 'Curso excluído com sucesso!')
    return redirect('gradehoraria:listar_cursos')


@login_required(login_url='/contas/login')
def editar_curso(request, id_curso):
    editarCurso = get_object_or_404(Curso, id_curso=id_curso)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=editarCurso)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados do curso alterados com sucesso!')
            return redirect('gradehoraria:listar_cursos')
        else:
            messages.error(request, 'Erro ao alterar dados do curso!')
    else:
        form = CursoForm(instance=editarCurso)
        return render(request, 'curso/adicionar_curso.html', {'form': form})


@login_required(login_url='/contas/login')
def adicionar_turma(request):
    if request.method == 'POST':
        form = TurmaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Turma cadastrada com sucesso!')
            return redirect('gradehoraria:listar_turmas')
        else:
            messages.error(request, 'Erro ao cadastrar turma!')
    else:
        form = TurmaForm()
    return render(request, 'turma/adicionar_turma.html', {'form': form})


@login_required(login_url='/contas/login')
def listar_turmas(request):
    turmas = Turma.objects.all()
    return render(request, 'turma/listar_turmas.html', {'turmas': turmas})


# FIXME: Criar confirmação de exclusão antes de persistir no banco - OK
@login_required(login_url='/contas/login')
def deleta_turma(request, id_turma):
    deleteTurma = Turma.objects.get(id_turma=id_turma).delete()
    messages.warning(request, 'Turma excluída com sucesso!')
    return redirect('gradehoraria:listar_turmas')


@login_required(login_url='/contas/login')
def editar_turma(request, id_turma):
    editar_turma = get_object_or_404(Turma, id_turma=id_turma)
    if request.method == 'POST':
        form = TurmaForm(request.POST, instance=editar_turma)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados da turma alterado com sucesso!')
            return redirect('gradehoraria:listar_turmas')
        else:
            messages.error(request, 'Erro ao alterar dados da turma')
    else:
        form = TurmaForm(instance=editar_turma)
        return render(request, 'turma/adicionar_turma.html', {'form': form})


@login_required(login_url='/contas/login')
def adicionar_sala(request):
    if request.method == 'POST':
        form = SalaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sala cadastrada com sucesso!')
            return redirect('gradehoraria:listar_salas')
        else:
            messages.error(request, 'Erro ao cadastrar sala!')
    else:
        form = SalaForm()
    return render(request, 'sala/adicionar_sala.html', {'form': form})


@login_required(login_url='/contas/login')
def listar_salas(request):
    salas = Sala.objects.all()
    return render(request, 'sala/listar_salas.html', {'salas': salas})


# FIXME: Criar confirmação de exclusão antes de persistir no banco - OK
@login_required(login_url='/contas/login')
def deleta_sala(request, id_sala):
    deleteSala = Sala.objects.get(id_sala=id_sala).delete()
    messages.warning(request, 'Sala excluída com sucesso!')
    return redirect('gradehoraria:listar_salas')


@login_required(login_url='/contas/login')
def editar_sala(request, id_sala):
    editar_sala = get_object_or_404(Sala, id_sala=id_sala)
    if request.method == 'POST':
        form = SalaForm(request.POST, instance=editar_sala)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados da sala alterado com sucesso!')
            return redirect('gradehoraria:listar_salas')
        else:

apps/gradehoraria/templates/oferta/adicionar_oferta.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Oferta - {{ block.super }}

{% endblock title %}

{% block body %}
    <div class="container">
        <h1>Oferta</h1>
        {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <form class="" action="." method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:"form-control"|attr:"autofocus" }}
                        {% if field.errors %}
                            <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
                        {% endif %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

apps/gradehoraria/templates/oferta/listar_ofertas.html
{% extends 'base.html' %}

{% block body %}
<style type="text/css">
    .filtroColuna{
        width:90%;
        border:solid 1px;
	   /* definimos o quão arredondado irá ficar nosso box */
	    border-radius: 6px;
    }
	</style>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
    <div class="container">
        <h1>Ofertas</h1>
        {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <table id="tab" class="table">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Curso</th>
                            <th>Turma</th>
                            <th>Disciplina</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in ofertas %}
                            <tr>
                                <td>{{ p.id_oferta }}</td>
                                <td>{{ p.curso }}</td>
                                <td>{{ p.turma }}</td>
                                <td>{{ p.disciplina }}</td>
                                <td>
                                    <a href="{% url 'gradehoraria:editar_oferta' p.id_oferta %}" class="btn btn-info btn-sm">Editar</a>
                                    <a href="{% url 'gradehoraria:deleta_oferta' p.id_oferta %}" class="btn btn-danger btn-sm confirm-delete" data-toggle="modal", data-target="#confirmDeleteModal" id="delete-{{ p.id_oferta }}">Excluir</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'gradehoraria:adicionar_oferta' %}" class="btn btn-primary" role="button">Adicionar Oferta</a>
                <script>
                function AdicionarFiltro(tabela, coluna) {
                    var cols = $("#" + tabela + " thead tr:first-child th").length;
                    if ($("#" + tabela + " thead tr").length == 1) {
                        var linhaFiltro = "<tr>";
                        for (var i = 0; i < cols; i++) {
                            linhaFiltro += "<th></th>";
                        }
                        linhaFiltro += "</tr>";

                        $("#" + tabela + " thead").append(linhaFiltro);
                    }

                    var colFiltrar = $("#" + tabela + " thead tr:nth-child(2) th:nth-child(" + coluna + ")");

                    $(colFiltrar).html("<select id='filtroColuna_" + coluna.toString() + "'  class='filtroColuna'> </select>");

                    var valores = new Array();

                    $("#" + tabela + " tbody tr").each(function () {
                        var txt = $(this).children("td:nth-child(" + coluna + ")").text();
                        if (valores.indexOf(txt) < 0) {
                            valores.push(txt);
                        }
                    });
                    $("#filtroColuna_" + coluna.toString()).append("<option>TODOS</option>")
                    for (elemento in valores) {
                        $("#filtroColuna_" + coluna.toString()).append("<option>" + valores[elemento] + "</option>");
                    }

                    $("#filtroColuna_" + coluna.toString()).change(function () {
                        var filtro = $(this).val();
                        $("#" + tabela + " tbody tr").show();
                        if (filtro != "TODOS") {
                            $("#" + tabela + " tbody tr").each(function () {
                                var txt = $(this).children("td:nth-child(" + coluna + ")").text();
                                if (txt != filtro) {
                                    $(this).hide();
                                }
                            });
                        }
                    });
                };
                AdicionarFiltro("tab", 3);
                </script>
            </div>
        </div>
        {% include 'partials/confirm_delete_modal.html' %}
    </div>
{% endblock body %}