apps/contas/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import urls
from django.contrib.auth import views as auth_views

from . import views

app_name = 'contas'

urlpatterns = [
    path('novo_usuario/', views.novo_usuario, name='novo_usuario'),
    path('login/', views.login_usuario, name='login_usuario'),
    path('logout/', views.logout_usuario, name='logout_usuario'),
    path('alterar-senha/', views.alterar_senha, name='alterar_senha'),



    # url('reset-senha-confirmacao/<key>\w+)/$', views.reset_senha_confirmacao, name='reset_senha_confirmacao'),

]

apps/gradehoraria/urls.py
from django.urls import path

from . import views

app_name = 'gradehoraria'

urlpatterns = [
    path('professores', views.listar_professores, name='listar_professores'),
    path('professores/adicionar/', views.adicionar_professor, name='adicionar_professor'),
    path('professores/editar/<int:id_professor>/', views.editar_professor, name='editar_professor'),
    path('professores/excluir/<int:id_professor>/', views.deleta_professor, name='deleta_professor'),

    path('cursos', views.listar_cursos, name='listar_cursos'),
    path('curso/adicionar/', views.adicionar_curso, name='adicionar_curso'),
    path('curso/editar/<int:id_curso>/', views.editar_curso, name='editar_curso'),
    path('curso/excluir/<int:id_curso>/', views.deleta_curso, name='deleta_curso'),

    path('disciplinas', views.listar_disciplinas, name='listar_disciplinas'),
    path('disciplina/adicionar/', views.adicionar_disciplina, name='adicionar_disciplina'),
    path('disciplina/editar/<int:id_disciplina>/', views.editar_disciplina, name='editar_disciplina'),
    path('disciplina/excluir/<int:id_disciplina>/', views.deleta_disciplina, name='deleta_disciplina'),

    path('turmas', views.listar_turmas, name='listar_turmas'),
    path('turma/adicionar/', views.adicionar_turma, name='adicionar_turma'),
    path('turma/editar/<int:id_turma>/', views.editar_turma, name='editar_turma'),
    path('turma/excluir/<int:id_turma>/', views.deleta_turma, name='deleta_turma'),  path('turmas', views.listar_turmas, name='listar_turmas'),

    path('salas', views.listar_salas, name='listar_salas'),
    path('sala/adicionar/', views.adicionar_sala, name='adicionar_sala'),
    path('sala/editar/<int:id_sala>/', views.editar_sala, name='editar_sala'),
    path('sala/excluir/<int:id_sala>/', views.deleta_sala, name='deleta_sala'),

    path('oferta/adicionar/', views.adicionar_oferta, name='adicionar_oferta'),
    path('oferta/listar/', views.listar_ofertas, name='listar_ofertas'),
    path('oferta/listar/<int:turma>/', views.listar_ofertas, name='listar_ofertas'),
    path('oferta/editar/<int:id_oferta>/', views.editar_oferta, name='editar_oferta'),
    path('oferta/excluir/<int:id_oferta>/', views.deleta_oferta, name='deleta_oferta'),

    path('parametros/adicionar/', views.adicionar_parametros, name='adicionar_parametros'),
    path('parametros/listar/', views.listar_parametros, name='listar_parametros'),
    path('parametros/editar/<int:id_parametro>/', views.editar_parametros, name='editar_parametros'),

    path('grade/gerar_grade/', views.gerarGradeHoraria, name='gerarGradeHoraria'),
    path('grade/listar_grades/', views.listar_grades, name='listar_grades'),
    path('grade/editar/<int:id_turma>/', views.editar_grade, name='editar_grade'),
    path('grade/mostrar/<int:id_turma>/', views.mostrar_grade, name='mostrar_grade'),
    path('grade/excluir/<int:paramTurma_id>/', views.deleta_grade, name='deleta_grade'),
    # path('grade/salvarGrade/<List:resultado>/', views.salvarGradeHoraria, name='salvarGradeHoraria'),

    #path('', views.gradeHoraria, name='hello_world'),
    #path('', views.index, name='index'),
]

gradehorariaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gradehoraria/', include('gradehoraria.urls', namespace='gradehoraria')),
    path('contas/', include('contas.urls', namespace='contas')),
    path('', include('core.urls', namespace='core')),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name='contas/password_reset.html'),
         name='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='contas/password_reset_sent.html'),
         name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='contas/password_reset_form.html'),
         name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='contas/password_reset_done.html'),
         name='password_reset_complete'),

    #path('grade/', TemplateView.as_view(template_name='grade.html')),
    #path('cadastrarProfessor', TemplateView.as_view(template_name='professor.html')),
    #path('', TemplateView.as_view(template_name='home.html')),
]

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>{% block title %} GradeExada{% endblock title%}</title>
  </head>

  <body>
    <h1>GradeExata</h1>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
       <div class="container">
          <a class="navbar-brand" href="/">GradeExata</a>
          {% if user.is_authenticated and user.is_staff %}
          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gradehoraria:listar_cursos' %}">Cursos <span class="sr-only">(atual)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gradehoraria:listar_turmas' %}">Turmas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gradehoraria:listar_disciplinas' %}">Disciplinas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gradehoraria:listar_professores' %}">Professores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gradehoraria:listar_salas' %}">Salas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gradehoraria:listar_ofertas' %}">Ofertas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gradehoraria:listar_parametros' %}">Grades</a>
              </li>
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if user.is_authenticated %}{{ user.username|default:user.get_full_name }}{% endif %}</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                  <a class="dropdown-item" href="{% url 'gradehoraria:listar_grades' %}">Grades Geradas</a>
                  <a class="dropdown-item" href="{% url 'contas:novo_usuario' %}">Cadastrar novo usuário</a>
                  <a class="dropdown-item" href="{% url 'contas:alterar_senha' %}">Alterar a senha</a>
                  <!--<a class="dropdown-item" href="">Editar Cadastro</a> -->
                  <a class="dropdown-item" href="{% url 'contas:logout_usuario' %}">Sair</a>
                </div>
              </li>
            </ul>
          </div>
            {% else %}
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if user.is_authenticated %}{{ user.username|default:user.get_full_name }}{% endif %}</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                 <!-- <a class="dropdown-item" href="{% url 'contas:novo_usuario' %}">Cadastrar novo usuário</a> -->
                  <a class="dropdown-item" href="{% url 'contas:alterar_senha' %}">Alterar a senha</a>
                  <!--<a class="dropdown-item" href="">Editar Cadastro</a> -->
                  <a class="dropdown-item" href="{% url 'contas:logout_usuario' %}">Sair</a>
                </div>
              </li>
            </ul>
          </div>
          {% endif %}
      </div>
    </nav>
    {% block body %}

    {% endblock body %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
        $(document).on('click', '.confirm-delete', function() {
          $('#confirmDeleteModal').attr('caller-id', $(this).attr('id'));
        });
        $(document).on('click', '#confirmDeleteButtonModal', function() {
          var caller = $('#confirmDeleteButtonModal').closest('.modal').attr('caller-id');
          window.location = $('#'.concat(caller)).attr('href');
        });
     </script>
  </body>
</html>

templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Página Inicial!</h1>
</body>
</html>